### PR TITLE
created 'Contact us page'

### PR DESCRIPTION
**Pull request by sahilit**
#5

### CODE REVIEW

**Comment by sahilit** [comment]
The contact us form will work on hosting to a server.

**Comment by coderwassananmol** [comment]
Hi @sahilit . Thanks for the PR. However, as I see it, your PR does not make the contact form responsive. Try testing it on devices with < 1024px and you will see the difference.
Also, please note that our current tech stack does not include PHP. This issue is only for static contact us page generation. I will open up another issue for server side integration. Once you are done with this one, please claim that issue. Thanks!

**Comment by sahilit** [comment]
Hi @coderwassananmol.
 Thanks for pointing out the issue. I have made the neccessary changes, so please check and merge the code. And also create the issue regarding the server side integration of the contact us section and also mention the tech stack which I can use.

**Comment by coderwassananmol** [comment]
> Hi @coderwassananmol.
> Thanks for pointing out the issue. I have made the neccessary changes, so please check and merge the code. And also create the issue regarding the server side integration of the contact us section and also mention the tech stack which I can use.

Please refer to the attached image. The contact us form is overlapping the Google Form.
WhatsApp Image 2019-04-23 at 2 35 38 PM

**Comment by sahilit** [comment]
The issue is occurring because of the google form section.
I think this issue will be solved in the 'Remove the horizontal scrollbar' #32

**Comment by sahilit** [comment]
Solved Google form Overlapping bug

**Comment by coderwassananmol** [comment]
> Solved Google form Overlapping bug

Sahil, the font size in the mobile seems pretty big. In the media queries, you can specify the font size for a particular width.
Just make sure it doesn't seem too big in the screens of small size.

**Comment by sahilit** [comment]
Solved #32 'Remove the horizontal scrollbar'

**Comment by Yuktichopra** [comment]
There are still some conflicts @sahilit

**Comment by sahilit** [comment]
@Yuktichopra solved

**Pull request merged**
